apiVersion: v1
kind: ConfigMap
metadata:
  name: skylark-config
  namespace: default
data:
  SKYLARK_API_PORT: "8081"
  RUST_LOG: "info"
  RUST_BACKTRACE: "full"
  DNS_SERVER: "10.152.183.10:53"
  GLOBAL_STATE_HOST: "10.0.0.243"
