apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pi5u2-single
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
        autoscaling.knative.dev/scale-down-delay: "20m"
    spec:
      nodeSelector:
        node-name: pi5u2
      runtimeClassName: wasmedge
      containers:
        - image: guelmino/skylark-ex-single:0.2.808
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          envFrom:
            - configMapRef:
                name: skylark-config
          env:
            - name: LOCAL_NODE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
