apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-pyclient
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: guelmino/skylark:pyclient
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
