apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-ex-client
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      nodeSelector:
        node-type: Sat
      runtimeClassName: wasmedge
      containers:
        - image: guelmino/skylark-ex-client:0.2.206
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          envFrom:
            - configMapRef:
                name: skylark-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
