apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pi5u1-write-data
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      nodeSelector:
        node-name: pi5u1
      runtimeClassName: wasmedge
      containers:
        - image: guelmino/skylark-write-data:0.1.1006
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          envFrom:
            - configMapRef:
                name: skylark-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOCAL_NODE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              cpu: "800m"       # ~ 0.25 vCPU
              memory: "512Mi"
            limits:
              cpu: "900m"       # ~ 0.5 vCPU
              memory: "512Mi"
