apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-ex-alarm
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: wasmedge
      containers:
        - image: guelmino/skylark-ex-alarm:0.2.502
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: DNS_SERVER
              value: "10.152.183.10:53"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
            - name: LOCAL_NODE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SKYLARK_API_PORT
              value: "30163"
