apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-ex-eo-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: guelmino/skylark-ex-eo-service:latest
          env:
            - name: DNS_SERVER
              value: "10.152.183.10:53"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_STREAM_KEY
              value: "eo_image_stream"
            - name: LOG_LEVEL
              value: "DEBUG"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
