apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-neighbors
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: guelmino/skylark-neighbors:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
