apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-neighbors
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: guelmino/skylark-neighbors:latest
          ports:
            - containerPort: 8080
