apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skylark-write-data-daemonset
  namespace: default
  labels:
    app: skylark-write-data
spec:
  selector:
    matchLabels:
      app: skylark-write-data
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
      labels:
        app: skylark-write-data
    spec:
      hostNetwork: true
      nodeSelector:
        node-name: pi5u2
      runtimeClassName: wasmedge
      containers:
        - name: skylark-write-data
          image: guelmino/skylark-write-data:0.1.1006
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
          envFrom:
            - configMapRef:
                name: skylark-config
          env:
            - name: LOCAL_NODE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: "800m"       # ~ 0.25 vCPU
              memory: "512Mi"
            limits:
              cpu: "900m"       # ~ 0.5 vCPU
              memory: "512Mi"
