apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skylark-neighbors-proxy
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: nginx:alpine  # Use Nginx as the proxy
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              value: http://skylark-neighbors.default.svc.cluster.local
