apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skylark-node-info-daemonset
  namespace: default
  labels:
    app: skylark-node-info
spec:
  selector:
    matchLabels:
      app: skylark-node-info
  template:
    metadata:
      labels:
        app: skylark-node-info
    spec:
      hostNetwork: true
      nodeSelector:
        node-type: Sat
      containers:
        - name: skylark-node-info
          image: guelmino/skylark-node-info:0.2.101
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
