apiVersion: v1
kind: Service
metadata:
  name: skylark-node-info-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: skylark-node-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31016
