apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skylark-node-info-daemonset
  namespace: default
  labels:
    app: skylark-node-info
spec:
  selector:
    matchLabels:
      app: skylark-node-info
  template:
    metadata:
      labels:
        app: skylark-node-info
    spec:
      hostNetwork: true
      containers:
        - name: skylark-node-info
          image: guelmino/skylark-node-info:0.2.109
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLOUD_LATENCY_LOWER
              value: "25"
            - name: CLOUD_LATENCY_UPPER
              value: "45"
            - name: SAT_LATENCY_LOWER
              value: "10"
            - name: SAT_LATENCY_UPPER
              value: "20"
